apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apic-pipeline-git
  namespace: ci
spec:
  encryptedData:
    GIT_PRIV_TOKEN: AgAogOX0Exml0o7QQxJwL3ozgSlUyTLu8ELEZd4zp4UxcRi/Rcw15X5+MkXWLLlsO/blAmJBLjNqdQRSquugSQiDU1RAelOnR57dCcQSyqaEcvI2amynJLatVhKocF9GVRKE6/qvAiuKzRyynH8w9JLt5ReHk1U+rctv25f6snkkUA4Ei+oKw8Om6b/ZvfgH2JTbEFK5oBp2br5/Z0jPgVdc5kyhHZeoOdEyLD2GawKH8ViHVtpWOXkFPnyjHVefdOvh6wB7LepiWVaV0jgDkeux19O48OTI+wJf/rV026z7yYc/TEbH9XHvmhNFFvnkj/Btj6zbRRCs6d1e2mdIVVzcN/EFB1VH6HtF7wkwOhCwgBQ91Woqe0UwPj30sRYY3M4puwanbjT13HRtekYbVWH/zxQl0j74z1rwySkTnao1h+3jL9in37zROPM9mEsy32L4evYBXjEe6npXeEacjlxcDuu3BM+Kuf72Olsk8QldDPSE3feF/Nn1WkfCJi1AvYcjDV/YaD6oRxSP6xDpj83LEjEMDAvxShEMX2oW5A9PnQvwpnNjSx0PEAdtEZpXC1/JBfY8Wh4Y81axe2YcyRPYLgUaOVDBJIr0WyU9CVIdZ5VxpOzbJK+L5IPyZX8f5jteuPly7XH1YKGMPuvubo7X9zIWX0zVW8QCojWOgJXe/ILgwdYpg+wZKOeo0UKivb9insG5k6vR3VV/ptG14yT+CifXJjn+fpaol/obFYyMdoRGDtaGERYH
    GIT_USERNAME: AgAaHehLNUtqreL2WyKMlU2cwv2IcESoMx6q8Jf6mo+/BY0dXMRIPNx07Y9kblLnKDimlgR6FiGIqtLHVU/MUlO6+MMvtaBCJxY69KTmgGUTS6sX4GL/QssZet4+k35wgJFkVz+EDpEJI7NnDjVbZ2kyJmKC342th+vQL/gNilgqIQMi40ynowM6Eus6/qspRLEf6sNasEG8kqPwB5dQ0OlUrznRza6wh0Bnx6r7O9AWFIz7WJgJ+Aq9UXV9KQ4491OevwPWFr6CMrAHeQP2NXCG6DqRaJ8dIHWLnk3zGB+lpKxBFFYXGvPjUAVan+9nMuPf7IlR8w/FUODxceQ889z8PyYKhgE69UD++yDkXG5MDwZWkwiCJDFX2cIKf0L516xT9Xc9i/U2zGTlDWVrJ0+rfidVluyku9nYRUB0Rg4DzFjfF6spxFkgUJlPKslv3q6TMOjVKDFdxu1/vYTKDdzus0/44/LHiwsp6nLGIgWzXUZ3g84UIU+v+TxYrpndOUaKx4WG+Kx1cqK6/klGM634+f6cBR8EmKo493MIqCmdKR98EP+TXMZhzwvx0PFiSEjhGXUK4ekh/NYYBnZEU/Jrx3PR5aJFMFLrrbS34XFAhzZCNbY2zFqGsV+OWw9/sMoFEmo393JMXH3nLTJXT0z8nQj1yB3Q5o8yApijY1ULNggk/zOrPARgTFNfPQQqEofZrGpgMMkycO8=
  template:
    metadata:
      creationTimestamp: null
      name: apic-pipeline-git
      namespace: ci

